/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'pavel' at '9/30/16 12:09 AM' with Gradle 2.12
 *
 * @author pavel, @date 9/30/16 12:09 AM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
