language: java

jdk:
  - oraclejdk8

# locations to cache for specific build
cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

# speed-up build according to
# https://dzone.com/articles/speed-up-gradle-build-on-travisci
install: echo "skip 'gradle assemble' step"
script: gradle build --continue

# code-coverage reporting
after_success:
  - gradle reportScoverage coveralls
